title: Gebaren waarnemen
hero_image: images/banner.png
description: Hoe gebruik je gebaren om een actie te activeren
version: 4
listed: false
copyedit: false
last_tested: "2023-09-25"
steps:
  - 
    title: Inleiding
