title: Sensing gestures
hero_image: images/banner.png
description: How to use gestures to trigger an action
version: 4
listed: false
copyedit: false
last_tested: "2023-09-25"
steps:
  - title: Introduction
