---
title: Aνίχνευση xειρονομιών
hero_image: images/banner.png
description: Πώς να χρησιμοποιήσεις χειρονομίες για να προκαλέσεις μια ενέργεια
version: 4
listed: false
copyedit: false
last_tested: "2023-09-25"
steps:
  - title: Εισαγωγή
