title: Détecter des gestes
hero_image: images/banner.png
description: Comment utiliser des gestes pour déclencher une action
version: 4
listed: false
copyedit: false
last_tested: "2023-09-25"
steps:
  - 
    title: Introduction
